# This docker-compose.dev.yml file is for local development only.

version: "3"

services:
  core:
    extends:
      file: ./docker-compose.yml
      service: core

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - core
    ports:
      - 8000:8000
    command: uvicorn api.app:app --host 0.0.0.0 --port 8000 --reload
    environment:
      API_KEY: retake-test-key
      OPENSEARCH_HOST: core
      OPENSEARCH_PORT: 9200
      OPENSEARCH_USER: admin
      OPENSEARCH_PASSWORD: admin
      OPENSEARCH_USE_TLS: False
      PGSYNC_HOST: pgsync
      PGSYNC_PORT: 7433
      PGSYNC_SSL_ENABLED: False
    volumes:
      - .:/app

  redis:
    extends:
      file: ./docker-compose.yml
      service: redis
    ports:
      - 6379:6379

  caddy:
    extends:
      file: ./docker-compose.yml
      service: caddy

  pgsync:
    build:
      context: ./sync
      dockerfile: Dockerfile
    ports:
      - 7433:7433
    sysctls:
      - net.ipv4.tcp_keepalive_time=200
      - net.ipv4.tcp_keepalive_intvl=200
      - net.ipv4.tcp_keepalive_probes=5
    labels:
      org.label-schema.name: "pgsync"
      org.label-schema.description: "Postgres to OpenSearch sync"
      com.label-schema.service-type: "daemon"
    depends_on:
      - core
      - api
      - redis
    command: uvicorn sidecar:app --host 0.0.0.0 --port 7433 --reload
    environment:
      LOG_LEVEL: WARNING
      ELASTICSEARCH_HOST: core
      ELASTICSEARCH_PORT: 9200
      ELASTICSEARCH_USER: admin
      ELASTICSEARCH_PASSWORD: admin
      ELASTICSEARCH_SCHEME: https
      ELASTICSEARCH_USE_SSL: True
      ELASTICSEARCH_VERIFY_CERTS: False
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_AUTH: redis
      ELASTICSEARCH: false
      OPENSEARCH: true

volumes:
  caddy_data:
  caddy_config:
