---
version: '3'

services:

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    # volumes:
    #   - ./postgresql.conf:/etc/postgresql/postgresql.conf
    # command: postgres -c config_file=/etc/postgresql/postgresql.conf

  elastic:
    image: elasticsearch:8.8.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ELASTIC_PASSWORD: elastic
      discovery.type: single-node

  # zookeeper:
  #   image: confluentinc/cp-zookeeper
  #   ports:
  #     - "2181:2181"
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: docker.io/bitnami/kafka:3.5
    # depends_on:
    #   - zookeeper
    ports:
      # - "29092:29092" 
      - "9092:9092"
    # environment:
    #   KAFKA_BROKER_ID: 1
    #   KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
    #   KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    #   KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
    #   KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    #   KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    #   KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    #   KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  schema-registry:
    image: bitnami/schema-registry:latest
    depends_on:
      # - zookeeper
      - broker
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKA_BROKERS: "PLAINTEXT://broker:9092"
      SCHEMA_REGISTRY_DEBUG: true

  cdc:
    build:
      context: .
      dockerfile: Dockerfile

  # ksqldb-server:
  #   image: confluentinc/ksqldb-server:0.29.0
  #   depends_on:
  #     - broker
  #     - schema-registry
  #   ports:
  #     - "8088:8088"
  #   volumes:
  #     - "./confluent-hub-components/:/usr/share/kafka/plugins/"
  #   environment:
  #     KSQL_LISTENERS: "http://0.0.0.0:8088"
  #     KSQL_BOOTSTRAP_SERVERS: "broker:9092"
  #     KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
  #     KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
  #     KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
  #     KSQL_CONNECT_GROUP_ID: "ksql-connect-cluster"
  #     KSQL_CONNECT_BOOTSTRAP_SERVERS: "broker:9092"
  #     KSQL_CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.storage.StringConverter"
  #     KSQL_CONNECT_VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
  #     KSQL_CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
  #     KSQL_CONNECT_CONFIG_STORAGE_TOPIC: "_ksql-connect-configs"
  #     KSQL_CONNECT_OFFSET_STORAGE_TOPIC: "_ksql-connect-offsets"
  #     KSQL_CONNECT_STATUS_STORAGE_TOPIC: "_ksql-connect-statuses"
  #     KSQL_CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
  #     KSQL_CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
  #     KSQL_CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
  #     KSQL_CONNECT_PLUGIN_PATH: "/usr/share/kafka/plugins"

  # ksqldb-cli:
  #   image: confluentinc/ksqldb-cli:0.29.0
  #   container_name: ksqldb-cli
  #   depends_on:
  #     - broker
  #     - ksqldb-server
  #   entrypoint: /bin/sh
  #   tty: true

  # webserver:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "1323:1323"
