version: '3'

services:
  core:
    image: public.ecr.aws/opensearchproject/opensearch:latest
    ports:
      - 9200:9200
      - 9600:9600
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=false
      - plugins.ml_commons.model_access_control_enabled=true
      - plugins.ml_commons.only_run_on_ml_node=false

  api:
    image: retake/retakesearch:latest
    depends_on:
      - core
    ports:
      - 8000:8000
    command: uvicorn api.app:app --host 0.0.0.0 --port 8000 --reload
    environment:
      API_KEY: retake-test-key
      OPENSEARCH_HOST: core
      OPENSEARCH_PORT: 9200
      OPENSEARCH_USER: admin
      OPENSEARCH_PASSWORD: admin
      OPENSEARCH_USE_TLS: False
      PGSYNC_HOST: pgsync
      PGSYNC_PORT: 7433
      PGSYNC_SSL_ENABLED: False
    volumes:
      - .:/app

  redis:
    image: redis
    command: redis-server --requirepass redis
    
  pgsync:
    image: retake/retakesync:latest
    ports:
      - 7433:7433
    sysctls:
      - net.ipv4.tcp_keepalive_time=200
      - net.ipv4.tcp_keepalive_intvl=200
      - net.ipv4.tcp_keepalive_probes=5
    labels:
      org.label-schema.name: "pgsync"
      org.label-schema.description: "Postgres to OpenSearch sync"
      com.label-schema.service-type: "daemon"
    depends_on:
      - core
      - api
      - redis
    environment:
      LOG_LEVEL: INFO
      ELASTICSEARCH_HOST: core
      ELASTICSEARCH_PORT: 9200
      ELASTICSEARCH_USER: admin
      ELASTICSEARCH_PASSWORD: admin
      ELASTICSEARCH_SCHEME: https
      ELASTICSEARCH_USE_SSL: True
      ELASTICSEARCH_VERIFY_CERTS: False
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_AUTH: redis
      ELASTICSEARCH: false
      OPENSEARCH: true
