[tool.poetry]
name = "retake"
version = "0.0.0"
description = "Open Source Infrastructure for Vector Data Streams"
authors = ["Ming Ying <ming.ying.nyc@gmail.com>", "Philippe NoÃ«l <philippemnoel@gmail.com>"]
readme = "README.md"
packages = [{include = "retake"}, {include = "core"}, {include = "streams"}]

[tool.poetry.dependencies]
python = "^3.9"
psycopg2-binary = "^2.9.6"
pydantic = "^2.0.2"
sentence-transformers = "^2.2.2"
tqdm = "^4.65.0"
types-psycopg2 = "^2.9.21.10"
types-tqdm = "^4.65.0.1"
pinecone-client = "^2.2.2"
elasticsearch = "^8.8.2"
cohere = "^4.12.0"
openai = "^0.27.8"
faust-streaming = "^0.10.14"
requests = "^2.31.0"
python-dotenv = "^1.0.0"
fastavro = "^1.8.0"
weaviate-client = "^3.22.1"
confluent-kafka = "^2.2.0"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
mypy = "^1.4.1"
pytest = "^7.4.0"
numpy = "^1.25.1"
types-requests = "^2.31.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
