[package]
name = "tokenizers"
version = { workspace = true }
edition = { workspace = true }

[features]
icu = ["rust_icu_ubrk", "rust_icu_sys", "rust_icu_uloc", "rust_icu_ustring"]

[dependencies]
anyhow = "1.0.87"
lindera-core = "0.27.2"
lindera-dictionary = "0.27.2"
lindera-tokenizer = { version = "0.27.2", features = [
  "cc-cedict-compress",
  "cc-cedict",
  "ipadic-compress",
  "ipadic",
  "ko-dic-compress",
  "ko-dic",
] }
once_cell = "1.19.0"
serde = "1.0.210"
serde_json = "1.0.128"
tantivy.workspace = true
tracing = "0.1.40"
strum_macros = "0.26.4"
strum = { version = "0.26.3", features = ["derive"] }

[dependencies.rust_icu_ubrk]
version = "5.0.0"
optional = true
features = ["]

[dependencies.rust_icu_sys]
version = "5.0.0"
optional = true

[dependencies.rust_icu_ustring]
version = "5.0.0"
optional = true

[dependencies.rust_icu_uloc]
version = "5.0.0"
optional = true

[dev-dependencies]
rstest = "0.18.2"

[package.metadata.cargo-machete]
ignored = ["rust_icu_common", "strum"]
