[package]
name = "tokenizers"
version = "0.8.5"
edition = "2021"

[features]
icu = ["rust_icu_ubrk", "rust_icu_sys", "rust_icu_uloc", "rust_icu_ustring"]

[dependencies]
anyhow = "1.0.86"
lindera-core = "0.27.1"
lindera-dictionary = "0.27.1"
lindera-tokenizer = { version = "0.27.1", features = [
  "cc-cedict-compress",
  "cc-cedict",
  "ipadic-compress",
  "ipadic",
  "ko-dic-compress",
  "ko-dic",
] }
once_cell = "1.18.0"
serde = "1.0.188"
serde_json = "1.0.105"
tantivy = { git = "https://github.com/paradedb/tantivy.git", package = "tantivy", rev = "c7f13ef" }
tracing = "0.1.40"

[dependencies.rust_icu_ubrk]
version = "5.0.0"
optional = true

[dependencies.rust_icu_sys]
version = "5.0.0"
optional = true

[dependencies.rust_icu_ustring]
version = "5.0.0"
optional = true

[dependencies.rust_icu_uloc]
version = "5.0.0"
optional = true

[dependencies.rust_icu_common]
version = "5.0.0"
optional = true

[dev-dependencies]
rstest = "0.18.2"
