[package]
name = "tokenizers"
version = { workspace = true }
edition = { workspace = true }

[features]
icu = ["rust_icu_ubrk", "rust_icu_sys", "rust_icu_uloc", "rust_icu_ustring"]

[dependencies]
anyhow = "1.0.96"
lindera = { version = "0.39.0", features = [
  "cc-cedict",
  "ipadic",
  "ko-dic",
  "compress",
] }
once_cell = "1.20.3"
serde = "1.0.218"
serde_json = "1.0.139"
tantivy.workspace = true
tracing = "0.1.41"
strum_macros = "0.27.1"
strum = { version = "0.27.1", features = ["derive"] }

[dependencies.rust_icu_ubrk]
version = "5.0.0"
optional = true

[dependencies.rust_icu_sys]
version = "5.0.0"
optional = true

[dependencies.rust_icu_ustring]
version = "5.0.0"
optional = true

[dependencies.rust_icu_uloc]
version = "5.0.0"
optional = true

[dev-dependencies]
rstest = "0.24.0"

[dependencies.rust_icu_common]
version = "5.0.0"
optional = true

[package.metadata.cargo-machete]
ignored = ["rust_icu_common", "strum"]
