apiVersion: v1
kind: Pod
metadata:
  name: stressgres-runner
  labels:
    app: stressgres-runner
spec:
  restartPolicy: Never
  imagePullSecrets:
    - name: dockerhub-secret
  containers:
    - name: stressgres
      image: us-central1-docker.pkg.dev/molten-verve-216720/paradedb-repository/stressgres
      imagePullPolicy: IfNotPresent
      command:
        - sleep
        - infinity
