#
# This docker-compose.local.yml file is for development of the Parade DBMS only. It builds
# Dockerfile, which is the full ParadeDB image with all extensions, and all other Parade DB services,
# to allow for complete testing of the ParadeDB system. It is not intended for production use.
#

version: "3.8"

services:
  paradedb:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        PG_VERSION_MAJOR: 15
        PG_BM25_VERSION: 0.0.0
        PG_CRON_VERSION: 1.6.0
        PG_NET_VERSION: 0.7.2
        PG_IVM_VERSION: 1.5.1
        PG_GRAPHQL_VERSION: 1.3.0
        PG_HASHIDS_VERSION: 1.2.1
        PG_JSONSCHEMA_VERSION: 0.1.4
        PG_REPACK_VERSION: ver_1.4.8
        PG_STAT_MONITOR_VERSION: 2.0.1
        PG_HINT_PLAN_VERSION: REL15_1_5_0
        PGML_VERSION: 2.7.8
        PGTAP_VERSION: 1.3.0
        PGVECTOR_VERSION: 0.5.0
        PGAUDIT_VERSION: 1.7.0
        POSTGIS_VERSION: 3.4.0
        PGROUTING_VERSION: 3.5.0
        PGSQL_HTTP_VERSION: 1.6.0
        HYPOPG_VERSION: 1.4.0
        RUM_VERSION: 1.3.13
        CITUS_VERSION: 12.0.0
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
      - "9700:9700"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - paradedb-local-ccache:/cache/ccache
      - paradedb-local-sccache:/root/.cache/sccache

  postgrest:
    image: postgrest/postgrest:v11.2.0
    depends_on:
      paradedb:
        condition: service_healthy
    environment:
      PGRST_DB_URI: postgres://myuser:mypassword@paradedb:5432/mydatabase
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: anonymous
      PGRST_JWT_SECRET: paradedb-api-key
    ports:
      - "3000:3000"

volumes:
  paradedb-local-ccache:
  paradedb-local-sccache:
