# workflows/check-typo.yml
#
# Check Typo
# Check Typo using codespell.

name: Check Typo

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

concurrency:
  group: check-typo-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  check-typo:
    name: Check Typo using codespell
    runs-on: ubicloud-standard-2
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Check Typo using codespell
        uses: codespell-project/actions-codespell@v2
        with:
          check_filenames: true
          ignore_words_file: .codespellignore
          # The `skip` parameter is a total mess, read up before adding.
          # https://github.com/codespell-project/codespell/issues/1915
          skip: "Cargo.lock,./tests"
