# workflows/lint-yaml.yml
#
# Lint YAML
# Lint YAML files using Prettier.

name: Lint YAML

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "**/*.yml"
      - "**/*.yaml"
      - ".github/workflows/lint-yaml.yml"
  workflow_dispatch:

concurrency:
  group: lint-yaml-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint-yaml:
    name: Lint YAML Files
    runs-on: depot-ubuntu-22.04-2
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Set up NodeJS Environment
        uses: actions/setup-node@v4

      - name: Install Prettier
        run: npm install -g prettier

      - name: Check YAML Formatting
        run: prettier --check "**/*.{yml,yaml}" --ignore-path .prettierignore
