# workflows/lint-pr-title.yml
#
# Lint PR Title
# Lint and enforce proper PR title format.

name: Lint PR Title

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  pull-requests: read

concurrency:
  group: lint-pr-title-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint-pr-title:
    name: Validate PR Title
    runs-on: depot-ubuntu-22.04-2
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout Git Repository
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
