# workflows/lint-docker.yml
#
# Lint Docker
# Lint Dockerfiles using Hadolint.

name: Lint Docker

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - ".github/workflows/lint-docker.yml"
      - "docker/**"
    workflow_dispatch:

concurrency:
  group: lint-docker-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint-docker:
    name: Lint Dockerfiles
    runs-on: ubicloud-standard-2
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4

      - name: Run Hadolint
        uses: jbergstroem/hadolint-gh-action@v1
        with:
          dockerfile: "**/Dockerfile*"
          error_level: 2 # Treat INFO as error
