# workflows/publish-stressgres-docker.yml
#
# Publish Stressgres (Docker)
# Publish Stressgres as a Docker image to Docker Hub. Stable
# releases publish Docker images with appropriate version tags.

name: Publish Stressgres (Docker)

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "GitHub tag version for this Docker image (e.g. 0.3.0)"
        required: true
        type: string

concurrency:
  group: publish-stressgres-docker-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  publish-stressgres-docker:
    name: Publish Stressgres Docker Image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v6

      # Cross-compilation is incredibly slow, so we use an external service called Depot to
      # speed up container builds for universal images. We could eventually replace this with
      # Docker Build Cloud once they add support for multiple concurrent builders.
      - name: Configure Depot CLI
        uses: depot/setup-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Docker Image tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: paradedb/stressgres
          tags: |
            type=raw,value=${{ github.event.inputs.release_version }}
            type=raw,value=v${{ github.event.inputs.release_version }}
            type=raw,value=latest

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image to Docker Hub
        uses: depot/build-push-action@v1
        with:
          context: .
          build-args: |
            RELEASE_TAG=v${{ github.event.inputs.release_version }}
          platforms: linux/amd64,linux/arm64
          file: docker/Dockerfile
          push: true
          sbom: true
          provenance: mode=max
          project: ${{ secrets.DEPOT_PROJECT }}
          token: ${{ secrets.DEPOT_TOKEN }}
          tags: ${{ steps.meta.outputs.tags }}
