# workflows/publish-stressgres-antithesis.yml
#
# Publish Stressgres (Antithesis)
# Publish Stressgres as a Docker image to the Antithesis registry, to be used
# for testing within Antithesis.

name: Publish Stressgres (Antithesis)

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "GitHub tag version for this Docker image (e.g. 0.3.0)"
        required: true
        type: string

concurrency:
  group: publish-stressgres-antithesis-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  publish-stressgres-antithesis:
    name: Publish Stressgres Docker Image to Antithesis Registry
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log Into Antithesis Registry
        uses: docker/login-action@v3
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.ANTITHESIS_REGISTRY_KEY }}

      - name: Extract Stressgres Metadata
        id: extract-stressgres-metadata
        uses: docker/metadata-action@v5
        with:
          images: us-central1-docker.pkg.dev/molten-verve-216720/paradedb-repository/stressgres
          tags: |
            type=sha
            type=raw,value=${{ github.event.inputs.release_version }}
            type=raw,value=v${{ github.event.inputs.release_version }}
            type=raw,value=antithesis-latest

      # Antithesis only supports x86_64 instruction set
      # https://antithesis.com/docs/getting_started/setup/?sid=6534.37&sterm=x86&marks=x86#containerize-your-software
      - name: Build and Push Stressgres Docker Image to Antithesis Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: |
            RELEASE_TAG=v${{ github.event.inputs.release_version }}
            COMMIT_SHA=${{ github.sha }}
          platforms: linux/amd64
          file: docker/Dockerfile
          push: true
          tags: ${{ steps.extract-stressgres-metadata.outputs.tags }}
          labels: ${{ steps.extract-stressgres-metadata.outputs.labels }}
