# workflows/test-stressgres-docker.yml
#
# Test Stressgres (Docker)
# Test building and running the Stressgres Docker Image.

name: Test Stressgres (Docker)

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main
    paths:
      - ".github/workflows/test-stressgres-docker.yml"
      - "docker/Dockerfile.stressgres"
      - "stressgres/**"
  workflow_dispatch:

concurrency:
  group: test-stressgres-docker-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test-stressgres-docker:
    name: Test Stressgres Docker Image
    runs-on: ubicloud-standard-8

    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v6

      - name: Login to DHI Registry
        uses: docker/login-action@v3
        with:
          registry: dhi.io
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Build Stressgres Docker Image
        run: |
          docker build \
            -f docker/Dockerfile.stressgres \
            -t paradedb/stressgres:${{ github.sha }} \
            .

      - name: Run the Stressgres Docker Image
        run: docker run -d --name stressgres paradedb/stressgres:${{ github.sha }}

      - name: Check that the Stressgres Docker Image Runs Properly
        run: |
          CONTAINER_ID=$(docker ps -aq --filter "name=stressgres")
          CONTAINER_STATUS=$(docker inspect -f '{{.State.Status}}' $CONTAINER_ID)
          echo "Stressgres container ID: $CONTAINER_ID"
          echo "Container status: $CONTAINER_STATUS"

          echo ""
          echo "Printing logs for the Stressgres Docker container..."
          docker logs $CONTAINER_ID

          # Fail the run if the container failed to start
          if [ "$CONTAINER_STATUS" = "exited" ]; then
            echo "Error: Container failed to start properly"
            exit 1
          fi
